# Generated by Django 4.1.7 on 2023-02-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=54, null=True)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'W trakcie pisania'), (2, 'Czeka na akceptację redaktora'), (3, 'Opublikowany')], default=1)),
                ('published', models.DateTimeField(null=True)),
                ('unpublished', models.DateField(null=True)),
            ],
        ),
    ]
