# Generated by Django 4.1.7 on 2023-02-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0005_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.IntegerField()),
                ('rating', models.IntegerField(choices=[(0, 'brak gwiazdek'), (1, '*'), (2, '**'), (3.0, '***'), (4.0, '****'), (5.0, '*****')])),
            ],
        ),
    ]
